### ISSUE TITLE
Display more PR info in the slack message

### ISSUE THREAD

**Issue by sweetmandm** [smashingboxes/code-review-bot#14]
I like the descriptive information you get on PRs for open-source projects (screenshot below). It'd probably be good to have a more space-efficient way to do it than slack's default link descriptions, but this might be an alternative to https://github.com/smashingboxes/code-review-bot/issues/12 if the bot can can get at the PR title, github username, and github user icon.
<img width="965" alt="screen shot 2016-02-22 at 1 59 31 pm" src="https://cloud.githubusercontent.com/assets/1136551/13229137/5d115496-d96d-11e5-813b-61831b5ee155.png">

**Comment by keeganbrown** [comment]
There's a substantial amount of rich formatting we can do. The bot already has access to PR title, GH user and Icon (that stuff is returned by the API by default). You can look in `mockGithub.js` to see what info the requests we're already making return.

**Comment by joshvc** [comment]
Note that the example in sweetman's post is an open source project. Slack pulls in a lot less from private repos.

**Comment by sweetmandm** [comment]
done in https://github.com/smashingboxes/code-review-bot/issues/17
