### ISSUE TITLE
No icon is shown for ERB files

### ISSUE THREAD

**Issue by dacur** [smashingboxes/code-review-bot#19]
My current PR is four ERB files and there is no icon assigned by the bot.

<img width="602" alt="screen shot 2016-02-23 at 4 33 31 pm" src="https://cloud.githubusercontent.com/assets/4250366/13267729/e12e52da-da4c-11e5-91ea-53dc95888f76.png">

PR in question:  https://github.com/smashingboxes/daimler_asp_rails/pull/96

Thanks

**Comment by joeyjoejoejr** [comment]
This is fixed by #32
