### ISSUE TITLE
CR bot needs to track PRs outside of memory, eg in redis.

### ISSUE THREAD

**Issue by keeganbrown** [smashingboxes/code-review-bot#27]
Right now, PRs are only being tracked in memory within the node thread. That's no good, especially if we want to deploy during the day. We need to move the storage to an external service, like redis.

**Comment by greg5green** [comment]
Can this be closed now with the recent PRs or is there still more to do here?

PS: I'm going to steal all this for project-assignments when I get the chance :D

**Comment by keeganbrown** [comment]
yep, I think this can be closed.
