### ISSUE TITLE
[Feature] New slack command for listing all open PRs

### ISSUE THREAD

**Issue by sb-tylermccraw** [smashingboxes/code-review-bot#35]
I'm not really sure how this would work.
But, it would be great to be able to enter a Slack command in any channel where code-review-bot is used to where users could get a quick glimpse of all open PRs.
Something like `/cr-list`?
It might get a little hectic because I'm sure there are a lot of stale PRs out there. But, this would force us to start cleaning up stale PRs and stale code.
Maybe it could be filtered down by team? Mobile/Frontend/Backend? `/cr-list mobile`?

**Comment by dkniffin** [comment]
This was implemented with #36 although it still needs a little work.
